"""empty message

Revision ID: 33090f1738f4
Revises: 2b5dfdf5bb04
Create Date: 2021-02-27 14:14:11.418362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33090f1738f4'
down_revision = '2b5dfdf5bb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'create_time')
    # ### end Alembic commands ###
